name: multi branches
run-name: ${{ github.actor }} is testing ${{ github.ref }}
on: 
  push: 
    branches: [ main, dev, test ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
